alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: das-allatorvosi-horse
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: bobocats-app
region: fra
services:
- environment_slug: node-js
  github:
    branch: main
    repo: markkovari/das-allatorvosi-horse
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: das-allatorvosi-horse
  source_dir: /

