# name: Deploy to DigitalOcean App Platform

on:
  push:
    # Trigger the workflow on pushes to the 'main' branch
    # You can change 'main' to 'master', 'production', or any other branch
    tags:
     - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest # The runner environment for the job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
          app_name: bobocats-app-test
          wait_for_deploy: true

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
          app_name: bobocats-app-prod
          wait_for_deploy: true
